---
title: "R Notebook"
output: html_notebook
---

```{r, echo=FALSE, results=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.width=4.5, fig.height=4)
library(ggplot2)
library(tidyverse)
library(olsrr)
library(caret)
library(texreg)
library(leaps)
```


```{r, echo=FALSE, results=FALSE}
df=read.csv("/Users/rumiallbert/Library/CloudStorage/GoogleDrive-rumiallbert@gmail.com/My Drive/Fei Tian Middletown /Fall 2022/Applied Regression Analysis/Final Project/data/model_df.csv")
#df$wage = df$wage*52
head(df)
```


```{r}
model = lm(value~., data=df)
summary(model)
plot(model)
```


```{r}
step = ols_step_both_aic(model)
```
```{r}
step$model
```



```{r}
df_clean = df
for (x in 0:1) {
  print(nrow(df_clean))
  model = lm(log(value)~ release_clause + wage+ potential + real_face + movement_balance + mentality_penalties + club_team_id + mentality_aggression+ attacking_crossing  + international_reputation + pace + league_level + power_stamina + overall + physic + power_jumping + skill_long_passing + age + nation_jersey_number + attacking_volleys + player_positions_FWD ,data=df_clean)

  #model_weighted = lm(wage~.,data=df_clean, weights= 1/value)
  stud = ols_plot_resid_stud(model, print_plot=F)
  df_clean = df_clean[-c(stud$outliers$observation), ]
}

summary(model)
plot(model)
# ols_plot_resid_stud(model)
```



```{r}
models <- regsubsets(value~., data = df, nbest=1, nvmax = NULL, really.big = T, method='seqrep')
summary_best_subset <- summary(models)
as.data.frame(summary_best_subset$outmat)
```

```{r}
which.max(summary_best_subset$adjr2)
```

```{r}
best_feats = summary_best_subset$which[13,]
best_feats
```


## Using BoxCox

```{r}
model_df = df

BCM <- BoxCoxTrans(df$value)
model_df$value <- predict(BCM, df$value)

head(model_df)
```
```{r}
hist(df$value, breaks=100)
```


```{r}
hist(model_df$value, breaks=100)
```

```{r}
df_clean = model_df[sample(nrow(model_df), 1000), ]
# df_clean = model_df
for (x in 0:5) {
  print(nrow(df_clean))

  # model = lm(log(value) ~  wage+ potential + real_face + movement_balance + mentality_penalties + club_team_id + mentality_aggression+ attacking_crossing  + international_reputation + pace + league_level + power_stamina + overall + physic + power_jumping + skill_long_passing + age + nation_jersey_number + attacking_volleys + player_positions_FWD, data=df_clean)

  
  model = lm(value ~ age + physic + wage + potential +  overall  + international_reputation , data=df_clean)
  stud = ols_plot_dffits(model, print_plot=F)
  df_clean = df_clean[-c(stud$outliers$observation), ]
  
}
summary(model)
plot(model, 1)
plot(model, 2)
# ols_plot_dffits(model)
ols_plot_cooksd_bar(model)
ols_plot_resid_stud(model)
```

```{r}
ano = anova(model)
library(htmlTable)
htmlTable(ano)
```


$\widehat{value}^{-.1}=350.8-0.06652age-0.001394physic+0.000003400wage+0.0251potential+1.536overall+0.2505reputation$

```{r}
library("PerformanceAnalytics")
myvars <- c('value', 'age' , 'physic' , 'mentality_aggression' , 'potential' , 'release_clause' , 'wage' , 'club_team_id' , 'movement_balance' , 'potential')
check = model_df[myvars]
check = check[sample(nrow(check), 5000), ]
chart.Correlation(check, histogram=TRUE, pch=25)

```

```{r}
model = lm(value~., data=df)
summary(model)
```

```{r}
k = ols_step_backward_p(model, p_val=.05)
```

```{r}
k
```

